# Use a specific OpenJDK base image for the Java Runtime Environment (JRE)
# Using JRE only is more lightweight than the full JDK
FROM eclipse-temurin:21_35-jre-alpine

# Copy the application JAR file into the container as app.jar
COPY ./build/libs/*.jar /app.jar

# Expose the port on which the Spring Boot app runs (default is 8080)
EXPOSE 8081

# Set the entry point command to run the application
ENTRYPOINT ["java"]
CMD ["-jar", "/app.jar"]
