# Use a specific OpenJDK base image for the Java Runtime Environment (JRE)
# Using JRE only is more lightweight than the full JDK
FROM eclipse-temurin:21_35-jre-alpine

# Expose the port on which the Spring Boot app runs (default is 8080)
EXPOSE 8082

# Set the entry point command to run the application
ENTRYPOINT ["java", "-jar", "/app.jar"]